"""add celery tables

Revision ID: 4fad0580aa59
Revises: 5451775580c9
Create Date: 2024-10-10 13:12:49.771274

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "4fad0580aa59"
down_revision = "5451775580c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "receipt",
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "receipt", "category", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "receipt", "category", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.drop_column("receipt", "task_id")
    # ### end Alembic commands ###
