"""Add budget table

Revision ID: ff3ca97b6ca0
Revises: e7b9a3bd3cb6
Create Date: 2024-08-06 11:34:50.339899

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ff3ca97b6ca0'
down_revision = 'e7b9a3bd3cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('other_expense', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_expense', sa.Float(), nullable=False),
    sa.Column('surplus', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('receipt', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('receipt_item', 'receipt_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipt_item', 'receipt_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('receipt', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('budget')
    # ### end Alembic commands ###
